# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

title: Yeoboya Tech Blog
subtitle: "2023년"
email: tech@yeoboya.com
name: Yeoboya
description: Yeoboya tech blog with dalla.
baseurl: ""
url: "https://tech-yeoboya.github.io/"
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

descriptions:
  - cat: 송영호
    desc: 플랫폼사업부 개발2팀 송영호

  - cat: 김현진
    desc: 플랫폼사업부 개발2팀 4파트 김현진


social:
  - name: Twitter
    icon: twitter
    username: TheBenCentra
    url: https://twitter.com/TheBenCentra
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: thebencentra
    url: ""
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: bencentra
    url: https://github.com/bencentra
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Ben Centra
    url: https://www.linkedin.com/pub/ben-centra/47/769/60a
    desc: Connect with me on LinkedIn
    share: true

  - name: YouTube
    icon: youtube
    username: ""
    url: ""
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: "dalla_live"
    url: https://www.instagram.com/dalla_live/
    desc: Follow me on Instagram
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username: ""
    url: ""
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
